#include "kheap.h"

// Symbol generated by the linker script (link.ld) marking the end of the binary
extern uint8_t _end;

// Maximum reserved heap size (4 MiB)
#define HEAP_SIZE (4 * 1024 * 1024)

static uintptr_t heap_start;
static uintptr_t heap_current;
static uintptr_t heap_end;

void kheap_init(void) {
    // The heap starts immediately after the end of the kernel
    heap_start = (uintptr_t)&_end;

    // Align the heap start to a 4 KB page boundary (4096 bytes)
    heap_start = (heap_start + 4095) & ~((uintptr_t)4095);

    heap_current = heap_start;
    heap_end = heap_start + HEAP_SIZE;
}

void *kmalloc_aligned(size_t size, size_t alignment) {
    if (alignment == 0) alignment = 8;

    // Ultra-fast alignment mask
    uintptr_t aligned_addr = (heap_current + (alignment - 1)) & ~(alignment - 1);

    // Check for out-of-memory
    if (aligned_addr + size > heap_end) {
        return NULL; // Out of memory
    }

    heap_current = aligned_addr + size;
    return (void *)aligned_addr;
}

void *kmalloc(size_t size) {
    return kmalloc_aligned(size, 8);
}